# Generated by Django 3.2.3 on 2023-07-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_alter_profile_tg_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tg_user_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID пользователя в Telegram'),
        ),
    ]
