# Generated by Django 3.2.3 on 2023-07-24 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_alter_profile_tg_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
